import random
import math
import numpy as np
from Environment4x1 import Environment4x1
from agent import Agent
#from planner import RoutePlanner
from simulator import Simulator
from PomdpenvironmentConverter import POMDPEnvironmentConverter
import copy



class LearningAgent(Agent):
    """ An agent that learns to drive in the Smartcab world.
        This is the object you will be modifying. """ 

    def __init__(self, env, learning=False, epsilon=1.0, alpha=0.5, resolution = 4):
        super(LearningAgent, self).__init__(env)     # Set the agent in the evironment 
        #self.planner = RoutePlanner(self.env, self)  # Create a route planner
        self.valid_actions = self.env.valid_actions  # The set of valid actions

        self.environmentmodel = POMDPEnvironmentConverter(copy.deepcopy(env),resolution) #the converter needs a model of the environment to make a few calculations.
                                # Set parameters of the learning agent
        self.learning = learning # Whether the agent is expected to learn
        self.Q = dict()          # Create a Q-table which will be a dictionary of tuples
        self.epsilon = epsilon   # Random exploration factor
        self.alpha = alpha       # Learning factor
        self.T = 1
        self.weight = 0.00001
        self.color = 'green'
        ###########
        ## TO DO ##
        ###########
        # Set any additional class parameters as needed


    def reset(self,  testing=False):
        """ The reset function is called at the beginning of each trial.
            'testing' is set to True if testing trials are being used
            once training trials have completed. """

        # Select the destination as the new location to route to
        #self.planner.route_to(destination)
        
        ########### 
        ## TO DO ##
        ###########
        # Update epsilon using a decay function of your choice
        # Update additional class parameters as needed
        # If 'testing' is True, set epsilon and alpha to 0
        #self.epsilon = math.cos(self.T*self.alpha)
        #self.epsilon = self.alpha**self.T
        
        
        
        self.epsilon = self.epsilon - 0.05
        self.environmentmodel.reset()
        
        
        if testing:
            self.epsilon = 0.0
            self.alpha = 0.0
        #else:
            #This is an adjusted sigmoid function
       #     threshold = 0.0004
       #     smallnum = 0.00001
       #     adjustment = (math.log(threshold)/(math.log(smallnum)*self.weight))

       #     self.epsilon = 1 / (1 + smallnum**(-self.weight*(self.T-adjustment)))
            #end sigmoid
            
            
        self.T = self.T + 1

        return None

    def build_state(self):
        """ The build_state function is called when the agent requests data from the 
            environment. The next waypoint, the intersection inputs, and the deadline 
            are all features available to the agent. """

        
        
        
        
        # Collect data about the environment
        #waypoint = self.planner.next_waypoint() # The next waypoint 
        inputs = self.environmentmodel.getState()           # Visual input - intersection light and traffic
        #deadline = self.env.get_deadline(self)  # Remaining deadline
        print inputs
        ########### 
        ## TO DO ##
        ###########
        # Set 'state' as a tuple of relevant data for the agent        
        state = (inputs)

        return state


    def get_maxQ(self, state):
        """ The get_max_Q function is called when the agent is asked to find the
            maximum Q-value of all actions based on the 'state' the smartcab is in. """

        ########### 
        ## TO DO ##
        ###########
        # Calculate the maximum Q-value of all actions for a given state
        value = self.Q[state]['left']
        for action in self.Q[state]:
            if value <= self.Q[state][action]:
                value = self.Q[state][action]

        return value


    def createQ(self, state):
        """ The createQ function is called when a state is generated by the agent. """

        ########### 
        ## TO DO ##
        ###########
        # When learning, check if the 'state' is not in the Q-table
        # If it is not, create a new dictionary for that state
        #   Then, for each action available, set the initial Q-value to 0.0
        if(self.learning):
            if(state in self.Q):
                return
        
        self.Q[state] = dict()
        for action in self.valid_actions:
            self.Q[state][action] = 0.0
        
            

        return


    def choose_action(self, state):
        """ The choose_action function is called when the agent is asked to choose
            which action to take, based on the 'state' the smartcab is in. """

        # Set the agent state and default action
        self.state = state
        #self.next_waypoint = self.planner.next_waypoint()
        
        #DriveActions = ['left','right','forward',None]
        action = None
        ########### 
        ## TO DO ##
        ###########
        # When not learning, choose a random action
        # When learning, choose a random action with 'epsilon' probability
        #   Otherwise, choose an action with the highest Q-value for the current state
        randomnum = random.uniform(0,1)
        if(randomnum <= self.epsilon):
            #for paction in self.valid_actions:
                #if self.Q[state][paction] is 0.0:
                #    action = paction
                #else:
                    #chosenaction = random.randint(0,3)
                    #action = self.valid_actions[chosenaction]
            
            action = random.choice(self.valid_actions)
        else:
            maxQ = self.get_maxQ(state)
            highqactions = []
            posibilities = -1
            for validact in self.valid_actions:
                if self.Q[state][validact] < maxQ:
                    continue
                highqactions = np.append(highqactions,validact)
                posibilities += 1
            chosenaction = random.randint(0,posibilities)
            action = highqactions[chosenaction]
            
        print action
            
            
        return action


    def learn(self, state, action, reward):
        """ The learn function is called after the agent completes an action and
            receives an award. This function does not consider future rewards 
            when conducting learning. """

        ########### 
        ## TO DO ##
        ###########
        # When learning, implement the value iteration update rule
        #   Use only the learning rate 'alpha' (do not use the discount factor 'gamma')
        if not self.learning:
            return
        
        qvalue = self.Q[state][action] * (1-self.alpha)
        reward = reward * self.alpha
        self.Q[state][action] = reward + qvalue
        return


    def update(self):
        """ The update function is called when a time step is completed in the 
            environment for a given trial. This function will build the agent
            state, choose an action, receive a reward, and learn if enabled. """

        state = self.build_state()          # Get current state
        self.createQ(state)                 # Create 'state' in Q-table
        action = self.choose_action(state)  # Choose an action
        reward = self.env.act(action) # Receive a reward
        self.learn(state, action, reward)   # Q-learn
        self.environmentmodel.Transition(action,self.env.sense()) #sense the environment and update model
        return
        

def run():
    """ Driving function for running the simulation. 
        Press ESC to close the simulation, or [SPACE] to pause the simulation. """

    ##############
    # Create the environment
    # Flags:
    #   verbose     - set to True to display additional output from the simulation
    #   num_dummies - discrete number of dummy agents in the environment, default is 100
    #   grid_size   - discrete number of intersections (columns, rows), default is (8, 6)
    env = Environment4x1()
    
    ##############
    # Create the driving agent
    # Flags:
    #   learning   - set to True to force the driving agent to use Q-learning
    #    * epsilon - continuous value for the exploration factor, default is 1
    #    * alpha - continuous value for the learning rate, default is 0.5
    agent = env.create_agent(LearningAgent,learning = True, epsilon = 0.9999, alpha=0.3,resolution=3)
    
    ##############
    # Follow the driving agent
    # Flags:
    #   enforce_deadline - set to True to enforce a deadline metric
    env.set_primary_agent(agent)

    ##############
    # Create the simulation
    # Flags:
    #   update_delay - continuous time (in seconds) between actions, default is 2.0 seconds
    #   display      - set to False to disable the GUI if PyGame is enabled
    #   log_metrics  - set to True to log trial and simulation results to /logs
    #   optimized    - set to True to change the default log file name
    sim = Simulator(env,update_delay = 0.3,log_metrics=True    ,optimized=False)
    
    ##############
    # Run the simulator
    # Flags:
    #   tolerance  - epsilon tolerance before beginning testing, default is 0.05 
    #   n_test     - discrete number of testing trials to perform, default is 0
    sim.run(n_test = 10)
<<<<<<< HEAD
    
    #line1 = [0.0, 0.3333333333333333, 0.0, 0.6666666666666666]
    #vectorline = agent.environmentmodel.translateNDpointto2D(line1)
    #print vectorline
=======

>>>>>>> df11c878d6e5aaae814194438e7a769c07156d06

if __name__ == '__main__':
    run()
